//
//  CommonPlateModels.swift
//  CommonPlateios
//
//  Created by faith on 7/9/26.
//
import Foundation

struct DiningSpot: Identifiable, Hashable {
    var id: String { name }
    let name: String
    /// Nil when the address is unavailable, e.g. a backend-sourced request whose
    /// wire representation is only a `vendor` name string. Not a fabricated "".
    let address: String?
}

enum RequestTiming: String, CaseIterable, Identifiable {
    case asap = "ASAP"
    case later = "Later"

    var id: String { rawValue }
}

/// Canonical lifecycle status. Backend wire values `requested`/`claimed`/`placed`
/// map to `.open`/`.claimed`/`.placed` — see RequestDTOs.swift for the wire mapping.
enum RequestStatus: String {
    case open = "Open"
    case claimed = "Claimed"
    case placed = "Placed"
}

struct FulfillmentDetails {
    let helperEmail: String
    let helperPhoneNumber: String
    let orderConfirmation: String
    let pickupTimeOrETA: String
    let noteToRequester: String
    let submittedAt = Date()
}

/// Local-simulation-only compatibility container for requester-private fields
/// that the canonical `FoodRequest` no longer stores directly. Only the
/// local/mock `FoodRequest` initializer (screens still running local
/// simulation, no backend connected) ever populates this. RequestService's
/// DTO-to-domain mapping must never construct one. Does not carry the claim
/// token — that stays exclusively in `RequestStore`'s `ActiveClaim`.
struct LocalRequestContext {
    let pickupName: String
    let email: String
    let phoneNumber: String
}

/// Canonical backend-backed request model. `id`, `createdAt`, `expiresAt`, and `status`
/// are backend-owned truth (see docs/week-2-integration-spec.md); they are never
/// computed or generated by iOS in the production path. Requester-private data
/// (pickup name, email, phone) is intentionally not modeled here — the public
/// wire shape never carries it, and a successful claim's pickup name belongs to
/// `RequestStore`'s active-claim state, not this model. See `LocalRequestContext`
/// for the local-simulation-only compatibility path.
struct FoodRequest: Identifiable {
    let id: String
    let diningSpot: DiningSpot
    let foodDescription: String
    let timing: RequestTiming
    let preferredPickupTime: Date?
    let createdAt: Date
    let expiresAt: Date
    var status: RequestStatus
    var fulfillmentDetails: FulfillmentDetails?
    /// Non-nil only for locally-simulated requests; see `LocalRequestContext`.
    var localContext: LocalRequestContext?

    /// Canonical initializer: all backend-owned values (`id`, `createdAt`,
    /// `expiresAt`, `status`) are supplied explicitly, never generated locally.
    /// This is the production construction path once DTOs are mapped to domain
    /// models (RequestService, not part of this task).
    init(
        id: String,
        diningSpot: DiningSpot,
        foodDescription: String,
        timing: RequestTiming,
        preferredPickupTime: Date?,
        createdAt: Date,
        expiresAt: Date,
        status: RequestStatus,
        fulfillmentDetails: FulfillmentDetails? = nil
    ) {
        self.id = id
        self.diningSpot = diningSpot
        self.foodDescription = foodDescription
        self.timing = timing
        self.preferredPickupTime = preferredPickupTime
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.status = status
        self.fulfillmentDetails = fulfillmentDetails
        self.localContext = nil
    }

    /// Temporary local/mock-compatible initializer for screens still using local
    /// simulation (no backend connected yet). Generates a local ID/timestamps and
    /// a client-side expiration; must not be used once screens are backend-backed.
    init(
        diningSpot: DiningSpot,
        foodDescription: String,
        pickupName: String,
        email: String,
        phoneNumber: String,
        timing: RequestTiming,
        preferredPickupTime: Date?
    ) {
        self.id = UUID().uuidString
        self.diningSpot = diningSpot
        self.foodDescription = foodDescription
        self.localContext = LocalRequestContext(pickupName: pickupName, email: email, phoneNumber: phoneNumber)
        self.timing = timing
        self.preferredPickupTime = preferredPickupTime
        self.createdAt = Date()
        switch timing {
        case .asap:
            self.expiresAt = createdAt.addingTimeInterval(5 * 60 * 60)
        case .later:
            self.expiresAt = (preferredPickupTime ?? createdAt).addingTimeInterval(5 * 60 * 60)
        }
        self.status = .open
        self.fulfillmentDetails = nil
    }

    var isExpired: Bool {
        Date() >= expiresAt
    }

    var isActive: Bool {
        status == .open && !isExpired
    }

    var shouldShowInASAPSection: Bool {
        switch timing {
        case .asap:
            return true

        case .later:
            guard let preferredPickupTime else {
                return false
            }

            let oneHourFromNow = Date().addingTimeInterval(60 * 60)
            return preferredPickupTime <= oneHourFromNow
        }
    }

    var timingDescription: String {
        switch timing {
        case .asap:
            return "ASAP"

        case .later:
            if let preferredPickupTime {
                return "Around \(preferredPickupTime.formatted(date: .omitted, time: .shortened))"
            } else {
                return "Later today"
            }
        }
    }

    var listTimingDescription: String {
        if shouldShowInASAPSection && timing == .later, let preferredPickupTime {
            return "Due around \(preferredPickupTime.formatted(date: .omitted, time: .shortened))"
        }

        return timingDescription
    }
}
